name: darnster_finance
description: Darnster Finance.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  provider: ^6.0.3

  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.1.0
  json_annotation: ^4.6.0
  url_launcher: ^6.1.2
  sizer: ^2.0.15
  auto_route: ^7.8.4
  auto_route_generator: ^7.3.2
  phosphor_flutter: 2.0.0
  collection: ^1.17.2
  carousel_slider: ^4.0.0
  google_maps_flutter: ^2.0.10
  google_maps_flutter_web: ^0.5.4+3
  mailer: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.3
  build_runner: ^2.4.8
  json_serializable: ^6.3.1
  

flutter:
  uses-material-design: true

  # Assets:
  assets:
    - assets/images/
    - assets/fonts/
    - web/icons/

# Fonts example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700